---
title: "sketch"
output: html_document
---

```{r}

library(tidyverse)

aprilBond %>% 
  mutate_at(vars(total, planned, tenure, coupon), as.numeric) %>% 
  mutate(code = str_extract(stocks, "[0-9]+(?=\\()")) %>% 
  mutate(code = case_when(
    nchar(code) == 4 ~ str_c(code, ".HK"),
    str_detect(code, "^6") ~ str_c(code, ".SH"),
    TRUE ~ str_c(code, ".SZ")
  )) %>% 
  # filter(lubridate::ymd(date) >= lubridate::ymd("2020-04-01")) %>% 
  mutate(stock_name = str_extract(stocks, "(?<=[0-9]{4,6}\\()[^\\(\\)]+(?=\\))")) %>% 
  select("name", "long_name", "stock_name") %>% 
  unique() %>% 
  writexl::write_xlsx("aprilnames.xlsx")
  
  
  
      group_by(stock_name, first) %>%
      summarise(n = n(), sum = sum(total)) %>% 
  filter(stock_name == "金融街") %>% 
  slice(1) %>% pull("sum") %>% paste0(., "亿")
  group_by(code, name) %>% 
  summarise(sum = sum(total, na.rm = TRUE)) %>% 
  drop_na() %>% 
  arrange(desc(sum))
  
  
```


```{r}

aprStock %>% inner_join(candidates, by = "stock_name")


candidates %>% anti_join(aprStock, by = "stock_name")
```





```{r}

colnames(names) <- c("code", "name")

names %>% 
  mutate(code = case_when(
    str_detect(code, "[A-Z]") ~ code, 
    nchar(code) == 5 ~ str_remove(code, "^0") %>% str_c(".HK"),
    str_detect(code, "^6") ~ paste0(code, ".SH"),
    TRUE ~ str_c(code, ".SZ")
  )) -> names
  writexl::write_xlsx("names.xlsx")
```



```{r}

names %>% anti_join(stock, by = c("code"))

stock$stock_name
```

```{r}

aprilnames %>% anti_join(stock, by = "stock_name") %>% 
  tidyr::drop_na()
```


```{r}


```









